config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  namespace :count_words do
    resource :by_file, only: [:create]
    resource :by_text, only: [:create]
    resource :result,  only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/count_words/by_files_controller.rb
class CountWords::ByFilesController < ApplicationController

  def create
    file = File.open(sanatize_params[:file])
    status, mssg = ValidateFileAndCountWordsService.new(file).()

    if status
      redirect_to count_words_result_path(:frequency => mssg)
    else
      flash[:error] = mssg
      redirect_to root_path
    end
  end

  private

  def sanatize_params
    params
      .require(:count_words)
      .permit(:file)
  end
end

app/controllers/count_words/by_texts_controller.rb
class CountWords::ByTextsController < ApplicationController

  def create
    text = sanatize_params[:text]
    status, mssg = CountWordFrequencyService.new(text.to_s).()

    if status
      redirect_to count_words_result_path(:frequency => mssg)
    else
      flash[:error] = mssg
      redirect_to root_path
    end
  end

  private

  def sanatize_params
    params
      .require(:count_words)
      .permit(:text)
  end
end

app/controllers/count_words/results_controller.rb
class CountWords::ResultsController < ApplicationController

  def show
    if params["frequency"].present?
      @frequencies = HashService.convert_hash_to_array_ordered(params["frequency"])
    else
      flash[:error] = "Lo sentimos, primero debes escribir o cargar un texto."
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/count_words/results/show.haml
.header
  %a.primary-button{href: "/"} volver
.general-container.without-padding-top
  %h1 Histograma
  .histogram
    %dl
      %dt
        Acá puedes ver la cantidad de palabras que tenía tu texto!
      - @frequencies.each do |word, count|
        %dd{:class => "percentage percentage-#{count}"}
          %span.text="#{word} #{count}"

app/views/home/index.haml
= render 'shared/flash'
.general-container
  %h1 Bienvenido a tu contador de palabras
  %p.description-template Puedes escribir un texto o cargar un archivo para el conteo de palabras

  .options
    .option
      %input#option-1{:checked => "checked", :name => "tab-group-1", :type => "radio"}/
      %label{:for => "option-1"} Escribir
      .content
        = simple_form_for :count_words, url: count_words_by_text_path, method: :post do |f|
          .text-input-action
            %p Acá puedes escribir el texto para realizar el conteo
            = f.input_field :text, as: :text, placeholder: "Escribir..."
            = f.submit "Cargar", class: 'primary-button'
    .option.right
      %input#option-2{:name => "tab-group-1", :type => "radio"}/
      %label{:for => "option-2"} Cargar
      .content
        = simple_form_for :count_words, url: count_words_by_file_path, method: :post do |f|
          .text-input-action
            %p.file Acá puedes cargar el archivo para realizar el conteo
            = f.input_field :file, as: :file, accept: ".txt"
            = f.submit "Subir", class: 'primary-button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FullstackTechnicalTest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_flash.haml
-flash.keys.each do |flash_key|
  %input{type: "checkbox", id:"toggle", class: "visually-hidden"}
  %div{class: "flash #{flash_key}"}
    %span=flash[flash_key]
    %label{for: "toggle"} x